version: '3.9'
services:

  booking:
    build: booking
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: booking
      SERVICE_TAGS: dev
    working_dir: /var/www/public

  nginx:
    image: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80"

  db:
    image: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: booking
      MYSQL_ROOT_PASSWORD: v684M2iJrbPG
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/

volumes:
  dbdata: